---
deployment:
  tasks:
<<<<<<< HEAD
    - export DEPLOYPATH=/home/idu5pqddbf6d/pmictest.com
=======
    - export DEPLOYPATH=/home/idu5pqddbf6d/repositories/omni2/
>>>>>>> dev
    - /bin/cp * $DEPLOYPATH
   